from __future__ import annotations

from typing import Any, Iterable, Iterator, Sequence

class LibSymbolsListWrapper(Sequence[Any]):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    def __getitem__(self, index: int) -> Any: ...

    def __len__(self) -> int: ...

    def load_symbol(self, *args: Any, **kwargs: Any) -> Any: ...
