from __future__ import annotations

from typing import Any, Iterable, Sequence


def GetBuildVersion() -> str: ...

F_Cu: int
B_Cu: int
In1_Cu: int
PCB_LAYER_ID_COUNT: int

LT_SIGNAL: int
LT_POWER: int
LT_USER: int
LT_MIXED: int
LT_JUMPER: int

FP_SMD: int
FP_THROUGH_HOLE: int
FP_VIRTUAL: int

PAD_ATTRIB_PTH: int
PAD_ATTRIB_NPTH: int

PAD_SHAPE_CIRCLE: int

PLOT_FORMAT_PDF: int
PLOT_FORMAT_SVG: int
PLOT_FORMAT_GERBER: int

SHAPE_T_SEGMENT: int
SHAPE_T_CIRCLE: int
SHAPE_T_ARC: int

ZONE_FILL_MODE_POLYGON: int
ZONE_FILL_MODE_HATCH_PATTERN: int


class LayerStack:
    def SetLayerName(self, layer_id: int, name: str) -> None: ...

    def SetLayerType(self, layer_id: int, layer_type: int) -> None: ...


class BOARD:
    def GetLayerStack(self) -> LayerStack: ...

    def SetLayerEnabled(self, layer_id: int, enabled: bool) -> None: ...

    def GetLayerID(self, name: str) -> int: ...

    def SetActiveLayer(self, layer_id: int) -> None: ...

    def GetActiveLayer(self) -> int: ...

    def IsLayerEnabled(self, layer_id: int) -> bool: ...

    def GetLayerName(self, layer_id: int) -> str: ...

    def GetLayerType(self, layer_id: int) -> int: ...

    def SetBoardEdgesBoundingBox(self, *args: Any, **kwargs: Any) -> None: ...

    def GetBoardEdgesBoundingBox(self) -> BOX2I: ...

    def GetLibraryPath(self) -> str: ...

    def GetDRCMarkers(self) -> Sequence[Any]: ...

    def Get3DViewer(self) -> Any: ...

    def SetDesignSettings(self, settings: Any) -> None: ...

    def GetDesignSettings(self) -> DESIGN_SETTINGS: ...

    def SetFileName(self, filename: str) -> None: ...

    def SetLayerStack(self, stack: LayerStack) -> None: ...

    def Add(self, item: Any) -> None: ...

    def GetFileName(self) -> str: ...

    def GetTitleBlock(self) -> TITLE_BLOCK: ...

    def FindFootprintByReference(self, reference: str) -> FOOTPRINT | None: ...

    def Remove(self, item: Any) -> None: ...

    def GetFootprints(self) -> Iterable[FOOTPRINT]: ...

    def GetNetInfo(self) -> NETINFO: ...

    def GetNetClasses(self) -> NETCLASS_MANAGER: ...

    def Tracks(self) -> Iterable[PCB_TRACK]: ...

    def Zones(self) -> Iterable[ZONE]: ...


class FOOTPRINT:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    def SetFootprintName(self, name: str) -> None: ...

    def GetFootprintName(self) -> str: ...

    def SetReference(self, value: str) -> None: ...

    def SetValue(self, value: str) -> None: ...

    def Add(self, item: Any) -> None: ...

    def SetPosition(self, position: Any) -> None: ...

    def SetOrientation(self, angle: int) -> None: ...

    def SetLayer(self, layer: int) -> None: ...

    def GetReference(self) -> str: ...

    def GetValue(self) -> str: ...

    def GetPosition(self) -> Any: ...

    def GetOrientation(self) -> int: ...

    def GetLayer(self) -> int: ...

    def GetAttributes(self) -> Any: ...

    def Pads(self) -> Iterable[PAD]: ...

    def FindPadByName(self, name: str) -> PAD | None: ...


class PAD:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    def Copy(self, other: PAD) -> None: ...

    def SetNumber(self, number: str | int) -> None: ...

    def SetShape(self, shape: int) -> None: ...

    def SetAttribute(self, attribute: int) -> None: ...

    def SetSize(self, size: Any) -> None: ...

    def SetDrillSize(self, size: Any) -> None: ...

    def SetPosition(self, position: Any) -> None: ...

    def GetPosition(self) -> Any: ...

    def GetOrientation(self) -> int: ...

    def GetLayer(self) -> int: ...


class NETCLASS:
    def __init__(self, name: str) -> None: ...

    def SetClearance(self, value: int) -> None: ...

    def SetTrackWidth(self, value: int) -> None: ...

    def SetViaDiameter(self, value: int) -> None: ...

    def SetViaDrill(self, value: int) -> None: ...

    def SetMicroViaDiameter(self, value: int) -> None: ...

    def SetMicroViaDrill(self, value: int) -> None: ...

    def SetDiffPairWidth(self, value: int) -> None: ...

    def SetDiffPairGap(self, value: int) -> None: ...

    def GetClearance(self) -> int: ...

    def GetTrackWidth(self) -> int: ...

    def GetViaDiameter(self) -> int: ...

    def GetViaDrill(self) -> int: ...

    def GetMicroViaDiameter(self) -> int: ...

    def GetMicroViaDrill(self) -> int: ...

    def GetDiffPairWidth(self) -> int: ...

    def GetDiffPairGap(self) -> int: ...


class ZONE:
    def __init__(self, board: BOARD | None = ...) -> None: ...

    def SetPriority(self, priority: int) -> None: ...

    def SetLayer(self, layer: int) -> None: ...

    def SetNet(self, net: Any) -> None: ...

    def SetLocalClearance(self, clearance: int) -> None: ...

    def SetMinThickness(self, thickness: int) -> None: ...

    def SetFillMode(self, mode: int) -> None: ...

    def Outline(self) -> ZONE_OUTLINE: ...


class PCB_SHAPE:
    def __init__(self, board: BOARD | None = ...) -> None: ...
    def SetShape(self, shape: int) -> None: ...

    def SetCenter(self, *args: Any, **kwargs: Any) -> None: ...

    def SetEnd(self, *args: Any, **kwargs: Any) -> None: ...

    def SetLayer(self, layer: int) -> None: ...

    def SetWidth(self, width: int) -> None: ...

    def SetStart(self, position: Any) -> None: ...


class PCB_TEXT:
    def __init__(self, board: BOARD | None = ..., *args: Any, **kwargs: Any) -> None: ...

    def SetText(self, text: str) -> None: ...

    def SetPosition(self, position: Any) -> None: ...

    def SetLayer(self, layer: int) -> None: ...

    def SetTextSize(self, size: Any) -> None: ...

    def SetTextThickness(self, thickness: int) -> None: ...

    def SetTextAngle(self, angle: int) -> None: ...

    def SetMirrored(self, mirrored: bool) -> None: ...


class PCB_TRACK:
    m_Uuid: Any

    def __init__(self, board: BOARD | None = ...) -> None: ...

    def SetStart(self, position: VECTOR2I) -> None: ...

    def SetEnd(self, position: VECTOR2I) -> None: ...

    def GetStart(self) -> VECTOR2I: ...

    def GetEnd(self) -> VECTOR2I: ...

    def SetLayer(self, layer: int) -> None: ...

    def SetWidth(self, width: int) -> None: ...

    def GetWidth(self) -> int: ...

    def SetNet(self, net: Any) -> None: ...


class PCB_VIA:
    def __init__(self, board: BOARD | None = ...) -> None: ...

    def SetPosition(self, position: VECTOR2I) -> None: ...

    def SetWidth(self, width: int) -> None: ...

    def SetDrill(self, drill: int) -> None: ...

    def SetLayerPair(self, top: int, bottom: int) -> None: ...

    def SetNet(self, net: Any) -> None: ...

    def GetWidth(self) -> int: ...

    def GetDrill(self) -> int: ...


class EXCELLON_WRITER:
    def __init__(self, board: BOARD) -> None: ...

    def SetFormat(self, metric: bool) -> None: ...

    def SetMapFileFormat(self, fmt: int) -> None: ...

    def SetOptions(self, *args: Any, **kwargs: Any) -> None: ...

    def CreateDrillandMapFilesSet(self, *args: Any, **kwargs: Any) -> None: ...


class PLOT_CONTROLLER:
    def __init__(self, board: BOARD) -> None: ...

    def OpenPlotfile(self, *args: Any, **kwargs: Any) -> Any: ...

    def ClosePlot(self) -> None: ...

    def GetPlotOptions(self) -> PLOT_OPTIONS: ...

    def PlotLayer(self, layer: int) -> None: ...


class ZONE_FILLER:
    def __init__(self, board: BOARD) -> None: ...

    def Fill(self, zones: Iterable[ZONE]) -> None: ...


class ZONE_OUTLINE:
    def Append(self, point: VECTOR2I) -> None: ...


class DRC:
    def __init__(self, board: BOARD) -> None: ...

    def Run(self) -> None: ...

    def GetMarkers(self) -> Iterable[DRC_MARKER]: ...

    def WriteReport(self, path: str) -> None: ...


class VECTOR2I:
    def __init__(self, x: int, y: int) -> None: ...

    x: int
    y: int


class BOX2I:
    def GetWidth(self) -> int: ...

    def GetHeight(self) -> int: ...

    def SetSize(self, size: VECTOR2I) -> None: ...

    def GetLeft(self) -> int: ...

    def GetRight(self) -> int: ...

    def GetTop(self) -> int: ...

    def GetBottom(self) -> int: ...


class TITLE_BLOCK:
    def GetTitle(self) -> str: ...

    def SetTitle(self, title: str) -> None: ...

    def SetCompany(self, company: str) -> None: ...

    def SetRevision(self, revision: str) -> None: ...

    def SetDate(self, date: str) -> None: ...

    def SetComment(self, index: int, text: str) -> None: ...

    def GetCompany(self) -> str: ...

    def GetRevision(self) -> str: ...

    def GetDate(self) -> str: ...

    def GetComment(self, index: int) -> str: ...


class PLOT_OPTIONS:
    def SetOutputDirectory(self, path: str) -> None: ...

    def SetScale(self, scale: float) -> None: ...

    def SetMirror(self, mirror: bool) -> None: ...

    def SetExcludeEdgeLayer(self, exclude: bool) -> None: ...

    def SetPlotFrameRef(self, enable: bool) -> None: ...

    def SetPlotValue(self, enable: bool) -> None: ...

    def SetPlotReference(self, enable: bool) -> None: ...

    def SetFormat(self, fmt: int) -> None: ...

    def SetUseGerberProtelExtensions(self, enable: bool) -> None: ...

    def SetUseAuxOrigin(self, enable: bool) -> None: ...

    def SetCreateGerberJobFile(self, enable: bool) -> None: ...

    def SetSubtractMaskFromSilk(self, enable: bool) -> None: ...

    def SetMonochrome(self, monochrome: bool) -> None: ...

    def SetPageSettings(self, settings: Any) -> None: ...


def LoadBoard(path: str) -> BOARD: ...


def SaveBoard(path: str, board: BOARD) -> None: ...


def FootprintLoad(library: str, name: str) -> FOOTPRINT: ...


class NETINFO_ITEM:
    def SetClass(self, netclass: NETCLASS) -> None: ...

    def GetNetCode(self) -> int: ...

    def GetNetname(self) -> str: ...

    def GetClassName(self) -> str: ...


class NETINFO:
    def FindNet(self, name: str) -> NETINFO_ITEM | None: ...

    def AddNet(self, name: str) -> NETINFO_ITEM: ...

    def GetNetCount(self) -> int: ...

    def GetNetItem(self, code: int) -> NETINFO_ITEM | None: ...


class NETCLASS_MANAGER:
    def Find(self, name: str) -> NETCLASS | None: ...

    def Add(self, netclass: NETCLASS) -> None: ...

    def __iter__(self) -> Iterable[NETCLASS]: ...


class DESIGN_SETTINGS:
    m_TrackMinWidth: int
    m_ViasMinSize: int
    m_ViasMinDrill: int
    m_MicroViasMinSize: int
    m_MicroViasMinDrill: int
    m_MinHoleDiameter: int
    m_RequireCourtyards: bool
    m_CourtyardMinClearance: int

    def SetMinClearance(self, value: int) -> None: ...

    def SetCurrentTrackWidth(self, value: int) -> None: ...

    def SetCurrentViaSize(self, value: int) -> None: ...

    def SetCurrentViaDrill(self, value: int) -> None: ...

    def SetCurrentMicroViaSize(self, value: int) -> None: ...

    def SetCurrentMicroViaDrill(self, value: int) -> None: ...

    def GetMinClearance(self) -> int: ...

    def GetCurrentTrackWidth(self) -> int: ...

    def GetCurrentViaSize(self) -> int: ...

    def GetCurrentViaDrill(self) -> int: ...

    def GetCurrentMicroViaSize(self) -> int: ...

    def GetCurrentMicroViaDrill(self) -> int: ...


class DRC_MARKER:
    def GetErrorCode(self) -> int: ...

    def GetDescription(self) -> str: ...

    def GetPos(self) -> VECTOR2I: ...
